#!/usr/bin/env python
from socket import socket, AF_INET, SOCK_DGRAM

if __name__=='__main__':

    UDP_IP = '127.0.0.1'
    UDP_PORT = 5005
    sock = socket(AF_INET, SOCK_DGRAM)
    sock.bind((UDP_IP,UDP_PORT))

    while True:
        data, addr = sock.recvfrom(1024)
        print "received:", data
